<?php

namespace App\Controller;

use System\HTTP\IRoutable;
use System\HTTP\Request\Request;
use System\HTTP\Request\RequestType;
use System\HTTP\Route;
use System\Navigation\Point;

class RulesController extends WebsiteController implements IRoutable
{

    /**
     * @var $_communityTab Point
     */
    private $_communityTab;

    /**
     * @var $_rulesTab Point
     */
    private $_rulesTab;

    public function onRegistration(): void
    {
        parent::onRegistration(); // TODO: Change the autogenerated stub

        $this->_communityTab = $this->getNavigation()->getById("Community");
        $this->_rulesTab = new Point("Community.Rules", "Benimmregeln", $this->getApp()->getConfig()->get("site", "url") . "community/rules", 9996);

        $this->_communityTab->add($this->_rulesTab);
    }

    /**
     * Returns the routes of the Controller
     * @return Route[]
     */
    public function getRoutes(): array
    {
        return [
            new Route(RequestType::GET, '/community/rules', 'rules')
        ];
    }

    public function onRequest(Request $request, Route $route, array $vars): void
    {
        $this->setPageTitle("Benimmregeln");

        $this->_communityTab->setActive(true);
        $this->_rulesTab->setActive(true);

        /**
         * @var $template Template
         */
        $template = $this->getView()->createTemplate("rules/Rules.tpl.php");
        $this->display($template);
    }
}